name: Hudu IT Documentation Platform
description: Hudu is an IT documentation platform designed to help IT teams organize and centralize their knowledge base. 
It offers features such as document management, knowledge sharing, and collaboration tools to make it easier for teams to create, manage, and access IT documentation.
With Hudu, IT teams can streamline their workflows, reduce downtime, and improve overall productivity.
instructions: null
changeLog:
  - date: 2022-08-10
    description: first release
links:
  - label: Website
    url: https://hudu.com/
  - label: Documentation
    url: https://support.hudu.com/hc/en-us
  - label: Self-Hosting ENV Generator
    url: https://self-hosting.usehudu.com/
contributors:
  - name: Mendy Green
    url: https://github.com/greenlighttec
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - workerServiceName
    - appServiceImage
    - cacheServiceName
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: app
    workerServiceName:
      type: string
      title: Worker Service Name
      default: worker    
    appServiceImage:
      type: string
      title: App Service Image
      default: hududocker/hudu:latest     
    databaseServiceName:
      type: string
      title: Database Service Name
      default: db
    cacheServiceName:
      type: string
      title: Cache Service Name
      default: redis       
